In [25]:
import tensorflow as tf
from numpy import float32

**different data structure => OD, 1D, 2D, more than 2D**

In [ ]:
# Define tensors with different structures | تعریف تنسور با بعد های مختلف

data_0D = tf.constant(5)
data_0D.shape

TensorShape([])

In [27]:
data_1D = tf.constant([1, 2, 3])
data_1D.shape

TensorShape([3])

In [28]:
data_2D = tf.constant([[1, 2, 3], [4, 5, 6]])
data_2D.shape

TensorShape([2, 3])

In [29]:
data_3D = tf.constant([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
data_3D.shape

TensorShape([2, 2, 3])

**Mathematical operations**

In [ ]:
# عملیات ریاضی مختلف در تنسور فلو

a = tf.constant([1, 2])
b = tf.constant([3, 4])

# Sum | جمع

# ستون ها باهم جمع میشن
sum = tf.add(a, b)
sum.numpy() # از نامپای استفاده میکنیم تا جزئیات نشون داده نشن

array([4, 6], dtype=int32)

In [ ]:
# Subtract | تفریق

subtract = tf.subtract(a, b)
subtract.numpy()

array([-2, -2], dtype=int32)

In [ ]:
# Division | تقسیم

division = tf.divide(a, b)
division.numpy()

array([0.33333333, 0.5       ])

In [ ]:
# Multiplication | ضرب

# توی تنسور فلو دو نوع ضرب وجود داره
# element wise | المنت وار
# المنت های متناظر رو توی هم ضرب میکنه یعنی ستون ها باهم ضرب میشن
e = tf.constant([[1, 2], [3, 4]])
f = tf.constant([[0, 1], [2, 3]])
ew = tf.multiply(e, f)
ew.numpy()

array([[ 0,  2],
       [ 6, 12]], dtype=int32)

In [ ]:
# Matrix multiplication | ضرب ماتریسی
mm = tf.matmul(e, f)
mm.numpy()

array([[ 4,  7],
       [ 8, 15]], dtype=int32)

In [ ]:
# Broadcasting | پخش کردن

# همه ی اعداد متغیر اِی رو در 4 ضرب میکنیم
a = tf.constant([1, 2, 3])
b = tf.constant(4) # =>[4, 4, 4]

c = tf.multiply(a, b)
c.numpy()


array([ 4,  8, 12], dtype=int32)

In [ ]:
# Reshape | تغییر سایز ماتریس یا بردار

a = tf.constant([1, 2, 3, 4, 5, 6])
a.shape # نمایش سایز

TensorShape([6])

In [37]:
b = tf.reshape(a, shape=(2, 3)) # تبدیل به یک ماتریس 2در3
b.shape

TensorShape([2, 3])

In [38]:
b.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
# Add dimension | اضافه کردن بعد به بردار یا ماتریس

a = tf.constant([1, 2, 3, 4, 5, 6])
a.shape

TensorShape([6])

In [40]:
# b = tf.expand_dims(a, 0) # -> [1, 6], [[1, 2, 3, 4, 5, 6]]
b = tf.expand_dims(a, -1)# -> [6, 1], [1],
                                     # [2],
                                     # [3],
                                     # [4],
                                     # [5],
                                     # [6]
b.shape, b.numpy()

(TensorShape([6, 1]),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]], dtype=int32))

In [ ]:
# انجام عملیات ریاضی روی هر کدوم از المان های یک بردار یا ماتریس

a = tf.constant([[1, 2], [3, 4.0]]) # 4.0 -> برای اینه که تنسور فلو، نوع داده رو اعشاری در نظر بگیره و خطایی پیش نیاد

# Square | رسوندن به توان 2

square = tf.square(a)
square.numpy()

array([[ 1.,  4.],
       [ 9., 16.]], dtype=float32)

In [ ]:
# Square root | محاسبه رادیکال

# tf.cast(..., dtype=float32) -> برای اینه که تنسور فلو، نوع داده رو به اعشاری تبدیل کنه و خطایی پیش نیاد
sr = tf.sqrt(tf.cast(a, dtype=float32))
sr.numpy()

array([[1.       , 1.4142135],
       [1.7320508, 2.       ]], dtype=float32)

In [43]:
a = tf.constant([[3, 7], [2, 9]], dtype=float32)
a.numpy()

array([[3., 7.],
       [2., 9.]], dtype=float32)

In [44]:
# Minimum | محاسبه کمترین المان ماتریس

# min = tf.reduce_min(a, axis=None) # 2 : محاسبه از بین تمام المان های ماتریس
# min = tf.reduce_min(a, axis=0) # 2, 7 : محاسبه از بین سطون ها که توی هر سطون کدوم المان کمتره
# min = tf.reduce_min(a, axis=1) # 3, 2 : محاسبه از بین سطر ها که توی هر سطر کدوم المان کمتره
min = tf.reduce_min(a) # 2 : محاسبه از بین تمام المان های ماتریس

min.numpy()

np.float32(2.0)

In [45]:
# Maximum | محاسبه بیشترین المان ماتریس

max = tf.reduce_max(a)
max.numpy()

np.float32(9.0)

In [46]:
# Average | محاسبه میانگین المان های ماتریس

avg = tf.reduce_mean(a)
avg.numpy()

np.float32(5.25)

In [47]:
# Standard deviation | محاسبه انحراف معیار المان های ماتریس

std = tf.math.reduce_std(a)
std.numpy()

np.float32(2.8613808)

In [48]:
# Sum & Multiplication | جمع و ضرب کل المان های ماتریس با هم

sum = tf.reduce_sum(a)
mul = tf.reduce_prod(a)

sum.numpy(), mul.numpy()

(np.float32(21.0), np.float32(378.0))