In [19]:
import numpy as np

In [20]:
# How to use Numpy | کتابخانه نامپای

# creat array | ساخت آرایه (لیست)

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [21]:
# creat matrix | ساخت ماتریس

b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [22]:
# shape | اندازه و شکل

print(a.shape, b.shape)

(4,) (2, 2)


In [23]:
# reshap | تغییر سایز و تعداد بعد لیست

c = a.reshape(4, 1)
print(c.shape)

(4, 1)


In [24]:
d = a.reshape(2, 2, -1) # باعث میشه اندازه رو خودش تایین کنه : -1
print(d.shape)

(2, 2, 1)


In [25]:
# concatenat | به هم چسبوندن لیست ها

list_1 = np.array([1, 2, 3, 4, 5])
list_2 = np.array([6, 7])
list_3 = np.array([8, 9, 10])

lists = np.concatenate([list_1, list_2, list_3])

print(lists)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
# Mathematical operations | عملیات ریاضی 

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result_jam = a + b
result_zarb = a * b

print(result_jam)
print(result_zarb)

[5 7 9]
[ 4 10 18]


In [27]:
# slic | انتخاب یک بخش از لیست

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

b = a[3:8:2] # From index 3 to index 8 with 2 steps | از ایندکس 3 تا ایندکس 8 دو تا دو تا

print(b)

[4 6 8]


In [28]:
# Choos a part of an array accord to the condition | انتخاب یک بخش از لیست با شرط

a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

b = a[a>3]

print(b)

[4 5 6 7 8]


In [29]:
# Sum of all elements of an array | جمع تمام المان های لیست

a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

b = np.sum(a)

print(b)

36


In [30]:
# Sort an array | مرتب سازی لیست

a = np.array([3, 7, 5, 9, 13, 4, 19, 11, 0, -5])

b = np.sort(a)

print(b)

[-5  0  3  4  5  7  9 11 13 19]


In [31]:
# Creat a matrix with random values | ساخت ماتریس با مقادیر رندوم

a = np.random.randint(1, 10, (3, 4)) # مقادیر شانسی بین 1 تا 10 و ماتریس 3 در 4

print(a)

[[7 5 4 4]
 [6 4 7 6]
 [7 2 5 1]]


In [32]:
# vertical stack | کنار هم گذاشتن عمودی چند لیست

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack([a, b])

print(c)

[[1 2 3]
 [4 5 6]]


In [33]:
# horizontal stack | کنار هم گذاشتن افقی چند لیست

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.hstack([a, b])

print(c)

[1 2 3 4 5 6]


In [34]:
# normaliz

a = np.array([1, 2, 3])
# Calculat avrage of the array | اول باید میانگین لیست رو حساب کنیم
mean_a = np.mean(a)
# Calculat STD | بعد باید انحراف از معیار رو حساب کنیم
std_a = np.std(a)
# حالا نورمالایز شده ماتریس اِی رو حساب میکنیم
norm_a = (a - mean_a)/std_a

print(norm_a)
print(np.mean(norm_a))
print(np.std(norm_a))

[-1.22474487  0.          1.22474487]
0.0
0.9999999999999999
